plugins {
    id "com.android.application"
}

android {
    namespace "com.nexaline.app"
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "com.nexaline.app"
        minSdk 23
        targetSdk 35
        versionCode 14
        versionName "1.0.13"
        buildConfigField "String", "NEXALINE_URL", "\"${project.findProperty("nexalineUrl") ?: "https://nexalineapp.xyz"}\""
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            shrinkResources false
        }
    }
}

dependencies {
    implementation "androidx.core:core:1.13.1"
}
